---
descriptor_schema: "https://raw.githubusercontent.com/sonata-nfv/tng-schema/master/function-descriptor/vnfd-schema.yml"

vendor: "eu.5gtango"
name: "vnf-cms"
version: "0.5"
author: "Ignacio Dominguez"
description: "Media-cms VNF descriptor."

cloudnative_deployment_units:
  - id: "cdu01"
    image: vastor80/5gtango:latest
    connection_points:
      - id: "int-api"
        port: 50000
      - id: "int-monitoring"
        port: 50010
  - id: "cdu02"
    image: pkarkazis/tng-stats-collector:latest
    parameters:
      env:
        VNF_STATS_URL: http://localhost:50000/status
        PW_URL: pushgateway.sonata.svc.cluster.local:9091
        INTERVAL: 2
      
# VNF connection points to the outside world
connection_points:
  - id: "api"
    interface: "ipv4"
    type: "serviceendpoint"
    port: 50000
  - id: "monitoring"
    interface: "ipv4"
    type: "serviceendpoint"
    port: 50010
  
# CNFs only use E-Tree links to map external ports to internal ports
virtual_links:
  - id: "api-link"
    connectivity_type: "E-Tree"
    connection_points_reference:
      - "api"
      - "cdu01:int-api"
  - id: "monitoring-link"
    connectivity_type: "E-Tree"
    connection_points_reference:
      - "monitoring"
      - "cdu01:int-monitoring"
