#descriptor_version: "1.0"
descriptor_schema: https://raw.githubusercontent.com/sonata-nfv/tng-schema/master/service-descriptor/nsd-schema.yml
vendor: "eu.sonata-nfv"
name: "mediapilot-service"
version: "0.9"
author: "Ignacio Dominguez @: atos"
description: "This NS provides the video streaming service for the immersive media pilot."

##
## The various network functions this service
## is composed of.
##
network_functions: 
  - vnf_id: "vnf-ma"
    vnf_vendor: "eu.5gtango"
    vnf_name: "vnf-ma"
    vnf_version: "0.9"
  - vnf_id: "vnf-mse-cache"
    vnf_vendor: "eu.5gtango"
    vnf_name: "vnf-mse-cache"
    vnf_version: "0.9"
  - vnf_id: "vnf-mse-transcode"
    vnf_vendor: "eu.5gtango"
    vnf_name: "vnf-mse-transcode"
    vnf_version: "0.9"
  - vnf_id: "vnf-cms"
    vnf_vendor: "eu.5gtango"
    vnf_name: "vnf-cms"
    vnf_version: "0.9"
  - vnf_id: "vnf-twitter"
    vnf_vendor: "eu.5gtango"
    vnf_name: "vnf-twitter"
    vnf_version: "0.9"
  - vnf_id: "vnf-youtube"
    vnf_vendor: "eu.5gtango"
    vnf_name: "vnf-youtube"
    vnf_version: "0.9"


##
## The NS connection points to the
## outside world.
##
connection_points:
  - id: "nscpexternal"
    interface: "ipv4"
    type: "external"

testing_tags: 
  - http

##
## The virtual links that interconnect
## the different connections points.
##
virtual_links:
  - id: "vlexternal"
    connectivity_type: "E-LAN"
    connection_points_reference:
      - "vnf-ma:rtmp"
      - "vnf-mse-cache:hls"
      - "vnf-cms:api"
      - "nscpexternal"
  - id: "vlapi"
    connectivity_type: "E-LAN"
    connection_points_reference:
      - "vnf-cms:api"
      - "vnf-ma:api"
      - "vnf-mse-cache:api"
      - "vnf-mse-transcode:api"
  - id: "aggregator-mse"
    connectivity_type: "E-Line"
    connection_points_reference:
      - "vnf-ma:rtmp"
      - "vnf-mse-transcode:rtmp"
  - id: "cms-monitoring"
    connectivity_type: "E-Line"
    connection_points_reference:
      - "vnf-cms:monitoring"
      - "vnf-twitter:monitoring"
  - id: "cms-youtube"
    connectivity_type: "E-Line"
    connection_points_reference:
      - "vnf-cms:youtube"
      - "vnf-youtube:youtube"
  - id: "cms-twitter"
    connectivity_type: "E-Line"
    connection_points_reference:
      - "vnf-cms:twitter"
      - "vnf-twitter:twitter"
