---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "mediapilot-slice-ma"
  version: "0.1"
  maintainer: "Ignacio Dominguez, Pol Alemany"
  description: "This is the 5GTANGO use case with a Network Slice composed by NSs using VNFs and CNFs"
files:
  - path: "Definitions/ma-nsd.yml"
    type: "application/vnd.5gtango.nsd"
  - path: "Definitions/ma-vnfd.yml"
    type: "application/vnd.5gtango.vnfd"
  - path: "Icons/cttc_atos_logo.png"
    type: "image/png"
  - path: "Licenses/LICENSE"
    type: "text/plain"